#!/usr/bin/env node
// Scans the images/ folder and regenerates images/manifest.js so the
// gallery picks up new photos. Run this after adding or removing photos:
//   node scripts/build-gallery.js
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const imagesDir = path.join(__dirname, "..", "images");
const manifestPath = path.join(imagesDir, "manifest.js");
const validExt = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif"]);
// Files used for page decoration rather than the slideshow.
const isExcluded = (name) => /background/i.test(name);

if (!fs.existsSync(imagesDir)) {
  fs.mkdirSync(imagesDir, { recursive: true });
}

function collect(dir, prefix) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? prefix + "/" + entry.name : entry.name;
    if (entry.isDirectory()) {
      out.push(...collect(path.join(dir, entry.name), rel));
    } else if (validExt.has(path.extname(entry.name).toLowerCase()) && !isExcluded(entry.name)) {
      out.push(rel);
    }
  }
  return out;
}

const files = collect(imagesDir, "").sort((a, b) =>
  a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" })
);

const contents =
  "// Auto-generated by scripts/build-gallery.js — do not edit by hand.\n" +
  "const galleryImages = " + JSON.stringify(files, null, 2) + ";\n";

fs.writeFileSync(manifestPath, contents);
console.log(`Wrote ${files.length} image(s) to images/manifest.js:`);
files.forEach((f) => console.log(" -", f));
